In [6]:
import numpy as np

kanto = np.array([73,67,43])
weights = np.array([0.3, 0.2, 0.5])

(kanto * weights).sum()
np.dot(kanto, weights)

v = 10

56.8

In [22]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

# np.matmul(climate_data, weights)
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [21]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

climate_data
# 2,2,3

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

weights = np.array([0.3, 0.2, 0.5])

# yields = np.matmul(climate_data, weights)
yields = climate_data @ weights

climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

climate_results
# yields


array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [36]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [50]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [90]:
z = np.random.random((10, 10)).max()
z

# continue 100 exercises from 14


0.9981218587395322